import React, { useEffect, useState } from 'react';
import type { JSX } from 'react';
import Link from '@docusaurus/Link';
import clsx from 'clsx';
import styles from './styles.module.css';

// Generated by scripts/generate-video-showcase.js at build time
import rawItems from '@site/src/data/video-showcase.json';

type ShowcaseItem = { title: string; url: string; video_asset: string };

const items = rawItems as ShowcaseItem[];
const INTERVAL = 3000;

const ChevronLeft = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
    <polyline points="15 18 9 12 15 6" />
  </svg>
);

const ChevronRight = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
    <polyline points="9 18 15 12 9 6" />
  </svg>
);

export default function VideoShowcase(): JSX.Element | null {
  const [index, setIndex] = useState(0);
  const [paused, setPaused] = useState(false);

  useEffect(() => {
    if (paused || items.length <= 1) return;
    const id = setInterval(() => setIndex((i) => (i + 1) % items.length), INTERVAL);
    return () => clearInterval(id);
  }, [paused]);

  if (items.length === 0) return null;

  const go = (n: number) => setIndex((n + items.length) % items.length);
  const multi = items.length > 1;

  return (
    <section
      className={styles.section}
      onMouseEnter={() => setPaused(true)}
      onMouseLeave={() => setPaused(false)}
    >
      <div className={styles.wrapper}>
        <div className={styles.slider}>
          <div className={styles.track} style={{ transform: `translateX(-${index * 100}%)` }}>
            {items.map((item) => {
              const isGif = /\.gif$/i.test(item.video_asset);
              return (
                <Link key={item.url} to={item.url} className={styles.slide}>
                  {isGif ? (
                    <img src={item.video_asset} alt={item.title} className={styles.media} />
                  ) : (
                    <video src={item.video_asset} className={styles.media} autoPlay muted loop playsInline />
                  )}
                  <div className={styles.overlay}>
                    <span className={styles.title}>{item.title}</span>
                  </div>
                </Link>
              );
            })}
          </div>
        </div>

        {multi && (
          <>
            <button className={clsx(styles.arrow, styles.arrowPrev)} onClick={() => go(index - 1)} aria-label="前へ">
              <ChevronLeft />
            </button>
            <button className={clsx(styles.arrow, styles.arrowNext)} onClick={() => go(index + 1)} aria-label="次へ">
              <ChevronRight />
            </button>
          </>
        )}
      </div>

      {multi && (
        <div className={styles.dots}>
          {items.map((_, i) => (
            <button
              key={i}
              className={clsx(styles.dot, i === index && styles.dotActive)}
              onClick={() => setIndex(i)}
              aria-label={`スライド ${i + 1}`}
            />
          ))}
        </div>
      )}
    </section>
  );
}
