# Auth0とGit Gatewayを利用し、mainブランチに保存する
backend:
  name: git-gateway
  branch: main
  # コミットメッセージのカスタマイズ（backendセクション内に配置）
  commit_messages:
    create: 'docs(diary): add new entry "{{slug}}"'
    update: 'docs(diary): revise entry "{{slug}}"'
    delete: 'docs(diary): remove entry "{{slug}}"'
    uploadMedia: 'docs(assets): add media "{{path}}"'
    deleteMedia: 'docs(assets): remove media "{{path}}"'

# メディアファイル（画像）の保存場所
media_folder: "static/img/uploads/diary"
public_folder: "/img/uploads/diary"

# 管理するコンテンツの定義
collections:
  - name: "diary"
    label: "Diary"
    folder: "diary"
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    editor:
      preview: true  # マークダウンプレビューを有効化

    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "Authors", name: "authors", widget: "hidden", default: ["hk"] }
      - { label: "目次を非表示", name: "hide_table_of_contents", widget: "boolean", default: false }
      - { label: "タグ", name: "tags", widget: "list", default: [] }
      - { label: "本文", name: "body", widget: "markdown" }

  # 将来の拡張用参照コレクション
  - name: "site_data"
    label: "サイトデータ"
    hide: true
    files:
      - label: "著者リスト"
        name: "authors"
        file: "blog/authors.yml"
        fields:
          - name: "authors"
            label: "著者"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "名前", name: "name", widget: "string" }
