# Netlify IdentityのGit Gatewayを利用するための設定
backend:
  name: git-gateway
  branch: main

# メディアファイル（画像）の保存場所
media_folder: "static/img/uploads/diary"
public_folder: "/img/uploads/diary"

# コミットメッセージのカスタマイズ設定（summary行を削除）
commit_messages:
  create: 'feat(diary): create new diary {{slug}}'
  update: 'fix(diary): update diary {{slug}}'
  delete: 'refactor(diary): delete diary {{slug}}'
  uploadMedia: 'chore(assets): upload {{path}}'
  deleteMedia: 'chore(assets): delete {{path}}'

# 管理するコンテンツの定義
collections:
  - name: "diary"
    label: "日記 (Diary)"
    folder: "diary"
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "Authors", name: "authors", widget: "hidden", default: ["hk"] }
      - { label: "目次を非表示 (Hide ToC)", name: "hide_table_of_contents", widget: "boolean", default: false }
      - { label: "タグ (Tags)", name: "tags", widget: "list" }
      - { label: "本文 (Body)", name: "body", widget: "markdown" }

  - name: "site_data"
    label: "サイトデータ"
    hide: true
    files:
      - label: "著者リスト"
        name: "authors"
        file: "blog/authors.yml"
        fields:
          - name: "authors"
            label: "著者"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "名前", name: "name", widget: "string" }
