# 最終版: 外部認証ゲートウェイを利用する設定
backend:
  name: github
  repo: hiroaki-com/hkdocs # あなたのリポジトリ
  branch: main
  # ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★
  # ★★★           認証設定の核心部分           ★★★
  # ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★
  # 外部の認証プロバイダーを利用することを指定
  auth_type: "pkce"
  app_id: aKQr0tFC0hih9IadqFZp99YcZnBUaj9p # あなたのAuth0 Client ID
  auth_endpoint: 'dev-m1dfi83ok2wmnn64.jp.auth0.com' # あなたのAuth0テナントの認可エンドポイント
  
# 画像などのメディアファイル
media_folder: "static/img/uploads/diary"
public_folder: "/img/uploads/diary"

# 管理するコレクション
collections:
  - name: "diary"
    label: "日記"
    folder: "diary"
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string", required: false }
      - { label: "内容", name: "body", widget: "markdown" }
