# Netlify IdentityのGit Gatewayを利用するための設定
backend:
  name: git-gateway
  branch: main

# メディアファイル（画像）の保存場所
media_folder: "static/img/uploads/diary"
public_folder: "/img/uploads/diary"

# 管理するコンテンツの定義
collections:
  - name: "diary"
    label: "日記 (Diary)"
    folder: "diary"
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      # 著者フィールドを編集画面から隠し、デフォルト値を 'hk' に固定
      - { label: "Authors", name: "authors", widget: "hidden", default: ["hk"] }
      - { label: "目次を非表示 (Hide ToC)", name: "hide_table_of_contents", widget: "boolean", default: false }
      - { label: "タグ (Tags)", name: "tags", widget: "list" }
      - { label: "本文 (Body)", name: "body", widget: "markdown" }

  # 著者データ参照用の架空コレクション
  # diaryコレクションでは直接使われなくなったが、将来的にblogなどを
  # CMS化する際に再利用できるため、残しておくと便利です。
  - name: "site_data"
    label: "サイトデータ"
    hide: true
    files:
      - label: "著者リスト"
        name: "authors"
        file: "blog/authors.yml"
        fields:
          - name: "authors"
            label: "著者"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "名前", name: "name", widget: "string" }
