# static/admin/config.yml
backend:
  name: git-gateway
  branch: main
  # Auth0を明示的に指定
  identity_url: "https://hkdocs.netlify.app/.netlify/identity"
  gateway_url: "https://hkdocs.netlify.app/.netlify/git/github"
  
# 以下は既存設定をそのまま維持
media_folder: "static/img/uploads/diary"
public_folder: "/img/uploads/diary"

collections:
  - name: "diary"
    label: "Diary"
    folder: "diary"
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    editor:
      preview: false

    commit_messages:
      create: 'feat(diary): create new diary entry "{{slug}}"'
      update: 'fix(diary): update diary entry "{{slug}}"'
      delete: 'refactor(diary): delete diary entry "{{slug}}"'
      uploadMedia: 'chore(assets): upload media file {{path}}'
      deleteMedia: 'chore(assets): delete media file {{path}}'
      openAuthoring: 'feat(diary): {{message}}'

    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "Authors", name: "authors", widget: "hidden", default: ["hk"] }
      - { label: "目次を非表示 (Hide ToC)", name: "hide_table_of_contents", widget: "boolean", default: false }
      - { label: "タグ (Tags)", name: "tags", widget: "list", default: [] }
      - { label: "本文 (Body)", name: "body", widget: "markdown" }

  - name: "site_data"
    label: "サイトデータ"
    hide: true
    files:
      - label: "著者リスト"
        name: "authors"
        file: "blog/authors.yml"
        fields:
          - name: "authors"
            label: "著者"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "名前", name: "name", widget: "string" }
